### ISSUE TITLE
Why geofence check all user-layer permission in every wfs transaction request?

### ISSUE THREAD

**Issue by ali-dashti** [geoserver/geofence#185]
We have more than thousand layer in geoserver and about hundred user in stand alone geofence.

We noticed something strange while editing feature by WFS transaction and that is that when we look at the postgresql logs, we find that geofence execute a number of SELECT query for all layers in geoserver. That means that geofence execute more than 1000 query for authorizing user for every wfs-t And that has slowed us down a lot. While we are editing one layer and the logical way is that geofence just check user permission on that layer. Not all layer in geoserver.

Is this really the behavior that happens in geofence?

**Comment by aaime** [comment]
GeoFence is just a security subsystem, it authorizes what the GeoServer catalog asks to authorize.I don't think it's doing a scan of all the layers by itself... but it's very likely that the WFS-T machinerywants to access all feature types.Why? Because the GML parser has been designed to be "schema driven", meaning, it needs to have a fullXML schema of any resources it might have to parse, before it starts parsing anything.
A WFS-T transaction can literally contain any of the feature types contained in GeoServer, so all of them have to be fetched, their list of attributes computed, and turned into a schema.

Are you seeing all these requests for every WFS-T call? The code in question has not been touched in many years, so I'm basing what I'm about to say on vague memories, but I would expect the structure to be computed once, and then kept as long as the list of layers is left unmodified. Any change to the list of layers, or to the configuration of one layer, is likely going to invalidate the cache and start the process again.
