### ISSUE TITLE
Advanced GS roles support

### ISSUE THREAD

**Issue by aaime** [geoserver/geofence#20]
<a href="https://github.com/mbarto"><img src="https://avatars.githubusercontent.com/u/2770528?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbarto](https://github.com/mbarto)**
_Wednesday Nov 20, 2013 at 14:35 GMT_
_Originally opened as https://github.com/geosolutions-it/geofence/issues/82_

----

Extend https://github.com/geosolutions-it/geofence/issues/77 so that we can support many roles, for example enabling RuleFilter to support a comma delimited list for groupname field

**Comment by etj** [comment]
The issue should be fixed with the implementation of this SPI:
https://github.com/geoserver/geofence/blob/master/src/services/core/services-api/src/main/java/org/geoserver/geofence/spi/UserResolver.java
whose default implemetation uses the actual DAOs:
https://github.com/geoserver/geofence/blob/master/src/services/core/services-impl/src/main/java/org/geoserver/geofence/services/DefaultUserResolver.java
