### ISSUE TITLE
GeoFence probe breaks Geoserver Authentication

### ISSUE THREAD

**Issue by cesarhein** [geoserver/geofence#58]
I want to preserve Geoserver Authentication method, because I need to create users with Admin permissions for a specific workspace. Everything is working before adding GeoFence jar files to ~/geoserver/WEB-INF/lib. After that, users can login into GeoServer, but they cant see his workspace. They just can see a empty list of workspaces.

**Comment by etj** [comment]
You can keep both (geoserver and geofence) authentication providers in geoserver. What is not working for you is the authorization part, because when geofence is installed, it completely replaces geoserver authorization logic.
If you are using the embedded geofence version, you may be interested in this implemented feature: https://github.com/geoserver/geofence/issues/67.
