### ISSUE TITLE
Using geofence and oauth2

### ISSUE THREAD

**Issue by kratosmat** [geoserver/geofence#88]
Hi all,
I am going to secure my geoserver by using openam as oauth2 authentication server. Is it possible to use users stored in openam to create rules in geofence?

Regards,
Matteo.

**Comment by afabiani** [comment]
Authentication and Authorization are two different concerns.

In order to Authenticate on GeoServer with OAuth2 you might want to take a look at this plugin and create the customization for your service

http://docs.geoserver.org/stable/en/user/community/oauth2/index.html


For Authorization (and creation of rules on GeoFence if needed) you need to create a customized Role Service for GeoServer I'm afraid.

Also for questions like this please use the GeoServer mailing list. GitHub Issues must be used only for signaling issues of the software.
