### ISSUE TITLE
problem building geofence 3.3.0: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project geofence-persistence: There are test failures.

### ISSUE THREAD

**Issue by jometho** [geoserver/geofence#94]
Dear Geofence developers,

I decided to build Geofence after failed attempts to use provided geofence.war.

I'm using Maven on Command line

I get this error: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project geofence-persistence: There are test failures.

I have tried to update the dependencies using `mvn dependency:resolve` and `mvn clean install -U` and didn't help.

What should I change? I cloned the project from here.

**Comment by etj** [comment]
Hi Steve, 
since the [CI](http://ares.boundlessgeo.com/jenkins/view/geofence/) is properly building GeoFence I guess there's a problem on your side. 
Please use the mailing list for this kind of support, also providing info about your environment and details about what's failing in your build (you are reporting a test failure, so please provide info about which test is failing and the related error).
   Cheers,
   Emanuele
