### ISSUE TITLE
GeoFence services URL

### ISSUE THREAD

**Issue by lolob** [geoserver/geofence#95]
Hi,

I use Geoserver version 2.9 and standalone Geofence 3.2 . I also have installed both probe and embedded based on the Geoserver version. I follow the documentation until the part of 'First steps' . From the picture below, I'm not able to get Geoserver to communicate with GeoFence. The Geofence standalone works fine. I can add user , instances and successfully test connection. I need to edit the GeoFence services URL box but it won't allow me to do so. Hope anyone can give some advise. 

![geofence](https://user-images.githubusercontent.com/15963902/29483698-1bfd66c4-84df-11e7-9b82-8a1f730856dc.png)

**Comment by etj** [comment]
You need to install in geoserver only the gs-geofence plugin: that's the one containing the probe, used to have geoserver connect to the external geofence.
I see you installed the gs-geofence-server plugin, which is used to have the geofence engine run in embedded mode inside geoserver (that's why the geofence URL is pre-set as "internal" and can not be edited ).

Please remove the .jar files that you installed from the geofence-server plugin and download the proper plugin from here
    https://github.com/geoserver/geofence#getting-geofence
You need to remove the other jars since there are some conflicting jars in the two packages that should be used in mutual exclusion.
